# CS 512 F24: Assignment 0 

Due by 9/1/2024 (0%)

**Name:** Tamilarasee Sethuraj

**Student ID:** A20553416



# Part A: Vector Operations

Let:
p=
[
2
−1
4 )
,q=
[
0
3
5)
,r=
[
1
−2
2 )

In [1]:
import numpy as np
p = np.array([2, -1, 4])
q = np.array([0, 3, 5])
r = np.array([1, -2, 2])

1. 3p+2q


In [2]:
print (3 * p + 2 * q)

[ 6  3 22]


2.  $\hat{\mathbf{p}}$ : a unit vector in the direction of p

In [3]:
magnitude_p = np.linalg.norm(p)
unit_vector_p = p / magnitude_p

print(unit_vector_p)

[ 0.43643578 -0.21821789  0.87287156]


3.  ∥ p∥ and the angle of p relative to the positive y-axis

In [4]:
e_y = np.array([0, 1, 0])

dot_product = np.dot(p, e_y)
magnitude_p = np.linalg.norm(p)
magnitude_e_y = np.linalg.norm(e_y)
cos_theta = dot_product / (magnitude_p * magnitude_e_y )
angle = np.degrees(np.arccos(cos_theta))

print(magnitude_p)
print(angle)

4.58257569495584
102.60438264837919


4. The direction cosines of p

In [6]:
magnitude_p = np.linalg.norm(p)
direction_cosines = p / magnitude_p
print(direction_cosines)

[ 0.43643578 -0.21821789  0.87287156]


5. The angle between p and q

In [7]:
dot_product = np.dot(p, q)
magnitude_p = np.linalg.norm(p)
magnitude_q = np.linalg.norm(q)
cos_theta = dot_product / (magnitude_p * magnitude_q )
angle = np.degrees(np.arccos(cos_theta))


print(angle)

50.490287713806076


6. p⋅ q and q ⋅ p


In [8]:
print(np.dot(p, q))
print(np.dot(q, p))

17
17


7. p ⋅ q using the angle between p and q

In [11]:
dot_product = magnitude_p * magnitude_q *  np.cos( np.deg2rad(angle))
print(dot_product)

17.0


8. The scalar projection of q onto  $\hat{\mathbf{p}}$ 

In [13]:
magnitude_unit_p = np.linalg.norm(unit_vector_p)

scalar_proj = np.dot(q,unit_vector_p) / magnitude_unit_p

print(scalar_proj)

3.709704134011871


9. A vector that is perpendicular to p

Cross product of any two vectors is perpendicular to both the vector. Assume a vector,u that is not parallel to p and compute cross product

In [14]:
u = np.array([0, 1, 0])
perpendicular_vector = np.cross(p, u)
print(perpendicular_vector)

[-4  0  2]


10. p×q and q× p

In [15]:
print(np.cross(p,q))
print(np.cross(q,p))

[-17 -10   6]
[17 10 -6]


11. A vector that is perpendicular to both p and q

In [16]:
perpendicular_vector = np.cross(p,q)
print(perpendicular_vector)

[-17 -10   6]


12. The linear dependency between p, q, and r

Construct a matrix M using p,q,r and find the determinant. If the determinant is zero, then p,q and r are linearly dependent

In [17]:
M = np.column_stack((p, q, r))
determinant = np.linalg.det(M)
print(determinant)

15.0


As determinant(M) is non zero, vectors p,q and r are linearly independent

13. $p^{T}q$ and $pq^{T}$

In [19]:
dot_product = np.dot(p, q)
outer_product = np.outer(p, q)
print("(p^T)q = ", dot_product)
print("p(q^T) = ",outer_product)

(p^T)q =  17
p(q^T) =  [[ 0  6 10]
 [ 0 -3 -5]
 [ 0 12 20]]


# Part B: Matrix Operations



In [49]:
X = np.array([[2, 1, 0],
              [-1, 3, 4],
              [3, 2, -2]])

Y = np.array([[4, -1, 2],
              [3, 0, -3],
              [1, 2, 1]])
Z = np.array([[2, 0, -1],
              [1, 4, 5],
              [3, 1, 2]])

s = np.array([
    -1,
    4,
    0
])

1. X+2Y

In [21]:
print (X + 2*Y)

[[10 -1  4]
 [ 5  3 -2]
 [ 5  6  0]]


2. X Y and Y X



In [23]:
print(np.dot(X,Y))
print(np.dot(Y,X))

[[11 -2  1]
 [ 9  9 -7]
 [16 -7 -2]]
[[15  5 -8]
 [-3 -3  6]
 [ 3  9  6]]


3. $(XY)^{T}$ and $Y^{T}X^{T}$

In [24]:
XY = np.dot(X,Y)
XY_T = np.transpose(XY)
print(XY_T)
Y_T_X_T = np.dot(np.transpose(Y),np.transpose(X))
print(Y_T_X_T)

[[11  9 16]
 [-2  9 -7]
 [ 1 -7 -2]]
[[11  9 16]
 [-2  9 -7]
 [ 1 -7 -2]]


4. |X ) and |Z) (see question A-12 -->The linear dependency between p, q, and r)

To find linear dependency of the row/column vectors of X, Z, find their determinants.
If the determinant is zero, then the row/column vectors of that respective matrix are linearly dependent

In [26]:
X_det = np.linalg.det(X)
Z_det = np.linalg.det(Z)
print(X_det,Z_det)

-17.999999999999996 17.0


Determinants of X and Z ae non zero and hence they are linearly independent

5. The matrix (either X, Y , or Z) in which the row vectors form an orthogonal set

In [28]:
X_X_T = np.dot(X,np.transpose(X))
Y_Y_T = np.dot(Y,np.transpose(Y))
Z_Z_T = np.dot(Z,np.transpose(Z))

print(X_X_T)
print(Y_Y_T)
print(Z_Z_T)

[[ 5  1  8]
 [ 1 26 -5]
 [ 8 -5 17]]
[[21  6  4]
 [ 6 18  0]
 [ 4  0  6]]
[[ 5 -3  4]
 [-3 42 17]
 [ 4 17 14]]


If the dot product of a matrix and its transpose is equal to the identity matrix, then it is orthogonal.
None of the matrices X,Y and Z are orthogonal and they do not have row vectors forming orthogonal set.

6. $X^{-1}$  and $Y^{-1}$ (see question B-5 -->Find matrix in which the row vectors form an orthogonal set)


In [46]:
X_1 = np.linalg.inv(X)
Y_1  = np.linalg.inv(Y)

product_X = np.dot(X_1,np.transpose(X_1))
product_Y = np.dot(Y_1,np.transpose(Y_1))

print(product_X)
print(product_Y)

[[ 0.66666667 -0.55555556  0.55555556]
 [-0.55555556  0.55555556 -0.5       ]
 [ 0.55555556 -0.5         0.52777778]]
[[3.96825397e-02 1.58730159e-02 4.17749735e-18]
 [1.58730159e-02 2.06349206e-01 4.24830239e-18]
 [4.17749735e-18 4.24830239e-18 7.14285714e-02]]


Since the dot product $X^{-1}X^{-T}$  and $Y^{-1}Y^{-T}$ are not identity matrices, they are not orthogonal and do not have row vectors forming orthogonal set

7. $Z^{-1}$ (see question B-4 ---> linear dependency)

In [48]:
Z_1 = np.linalg.inv(Z)
print(Z_1*17)
Z_1_det = np.linalg.det(Z_1)
print(Z_1_det)

[[  3.  -1.   4.]
 [ 13.   7. -11.]
 [-11.  -2.   8.]]
0.0588235294117647


Determinant of $Z^{-1}$ is non zero and hence it is linearly independent

8. The product Xs

In [50]:
print(np.dot(X,s))

[ 2 13  5]


9. The scalar projection of the rows of X onto the vector s (with s normalized)

In [52]:

magnitude_s = np.linalg.norm(s)
s_normalized = s / magnitude_s
scalar_projections = np.dot(X, s_normalized)
print(scalar_projections)

[0.48507125 3.15296313 1.21267813]


10. The vector projection of the rows of X onto the vector s (with s normalized)

Scalar projection an be used to calculate vector projection

In [53]:
vector_projections = scalar_projections[:, np.newaxis] * s_normalized
print(vector_projections)

[[-0.11764706  0.47058824  0.        ]
 [-0.76470588  3.05882353  0.        ]
 [-0.29411765  1.17647059  0.        ]]


11. The linear combination of the columns of X using the elements of s

This is same as the dot product of X and s

In [54]:
print(np.dot(X, s))


[ 2 13  5]


12. The solution t for the equation Y t=s

In [56]:
t = np.linalg.solve(Y, s)
print(t)

[ 0.33333333  0.33333333 -1.        ]


13. The solution t for the equation Z t=s and the reason for it (see question B-7)

In [57]:
t = np.linalg.solve(Z, s)
print(t)

[-0.41176471  0.88235294  0.17647059]


# Part C: Eigenvalues and Eigenvectors


In [58]:
M = np.array([
    [3, 2],
    [-1, 4]
])

N = np.array([
    [5, -3],
    [-3, 6]
])

P = np.array([
    [2, 4],
    [4, 8]
])

1. The eigenvalues and corresponding eigenvectors of M

In [59]:
M_values, M_vectors = np.linalg.eig(M)
print(M_values)
print(M_vectors)

[3.5+1.32287566j 3.5-1.32287566j]
[[0.81649658+0.j         0.81649658-0.j        ]
 [0.20412415+0.54006172j 0.20412415-0.54006172j]]


2. The dot product between the eigenvectors of M

In [60]:
M_eigenvector1 = M_vectors[:, 0]
M_eigenvector2 = M_vectors[:, 1]

print(np.dot(eigenvector1, eigenvector2))

(1.0000000000000002+0j)


3. The dot product between the eigenvectors of N

In [62]:
N_values, N_vectors = np.linalg.eig(N)
print(N_values)
print(N_vectors)

N_eigenvector1 = N_vectors[:, 0]
N_eigenvector2 = N_vectors[:, 1]

print(np.dot(N_eigenvector1, N_eigenvector2))

[2.45861873 8.54138127]
[[-0.76301998  0.6463749 ]
 [-0.6463749  -0.76301998]]
0.0


4. The property of the eigenvectors of N and the reason for it 


From C-3, we see that the dot product of eigen vectors is zero. The eigen vectors are orthogonal to each other. This is because the matrix N is symmetric. N = $N^{T}$

5. The value of a trivial solution t to the equation Pt=0

In [63]:
trivial_solution = np.array([0, 0])

verification = np.dot(P, trivial_solution)

print(verification)


[0 0]


Dot product of P and t = 0 shows that the trivaial solution for t = [0, 0]

6. The value of two non-trivial solutions t to the equation Pt=0

In [66]:
from scipy.linalg import null_space
null_space_P = null_space(P)
print(null_space_P)

[[-0.89442719]
 [ 0.4472136 ]]


7. The only solution t to the equation M t=0 and the reason for having a single solution

In [69]:
det_M = np.linalg.det(M)
print(det_M)
if det_M!=0:
    M_1 = np.linalg.inv(M)
    print(M_1)


14.000000000000004
[[ 0.28571429 -0.14285714]
 [ 0.07142857  0.21428571]]


Det(M) is non zero and $M^{-1}$ exists. This implies that from Mt = 0, the solution for t is trivial. t = [0, 0]

# Part D: Neural Networks Basics

1. Given a neuron with input values x1=0.5, x2=−0.8, and x3=0.3, weights w1=0.4,
w2=−0.6, and w3=0.9, and a bias b=0.2, compute the output of the neuron before 
applying any activation function.


In [70]:
x1 = 0.5
x2 = -0.8
x3 = 0.3
w1 = 0.4
w2 = -0.6
w3 = 0.9
b = 0.2


z = w1 * x1 + w2 * x2 + w3 * x3 + b

print(z)


1.15


2. Using the output computed in the previous question, apply the sigmoid activation 
function to find the activation value.

In [71]:
output = 1 / (1 + np.exp(-z))
print(output)

0.759510916949111


3. Given the same input values and weights as in question 1, compute the output of the 
neuron after applying a ReLU activation function

In [72]:
relu_activation = max(0, z)
print(relu_activation)

1.15


4. Given a neural network layer with weights W h, bias bh, and input x. Compute the output of the layer using ReLU activation

In [74]:
W_h = np.array([
    [0.4, 0.3],
    [0.2, 0.7]
])

b_h = np.array([
    0.1,
    -0.1
])

x = np.array([
    1,
    2
])

y = np.dot(W_h, x) + b_h
y_relu = np.maximum(0, y)
print(y_relu)


[1.1 1.5]


5. Feed the output of the layer from the previous question into an output layer with 
weights W o, bias bo, as follows:
W o=[ 0.5 −0.3) ,bo=[ 0.1)
compute the output of the layer using sigmoid activation.


In [75]:
W_o = np.array([0.5, -0.3])
b_o = np.array([0.1])
y_output = np.dot(W_o, y_relu) + b_o

output= 1 / (1 + np.exp(-y_output))

print(output)


[0.549834]
